nodeLinker: node-modules

npmScopes:
  session-foundation:
    npmAlwaysAuth: false
    npmRegistryServer: "http://vps-cfbca183.vps.ovh.ca:4873"

patchFolder: patches

unsafeHttpWhitelist:
  - vps-cfbca183.vps.ovh.ca

yarnPath: .yarn/releases/yarn-4.1.1.cjs
