yarnPath: .yarn/releases/yarn-4.0.2.cjs
patchFolder: patches
nodeLinker: node-modules

unsafeHttpWhitelist: ['vps-cfbca183.vps.ovh.ca']
npmScopes:
  'session-foundation':
    npmAlwaysAuth: false
    npmRegistryServer: http://vps-cfbca183.vps.ovh.ca:4873
