nodeLinker: node-modules

npmScopes:
  session-foundation:
    npmAlwaysAuth: false
    npmRegistryServer: 'https://verdaccio.oxen.rocks'

patchFolder: patches

yarnPath: .yarn/releases/yarn-4.1.1.cjs
