name: 'Run Android Tests'
description: 'Run Android tests with specified configuration'

inputs:
  PLATFORM:
    description: 'Platform to test (android/ios)'
    required: true
  RISK:
    description: 'Risk level to test'
    required: true
  WORKERS_COUNT:
    description: 'Number of Playwright workers'
    required: true
  DEVICES_PER_TEST:
    description: 'Number of devices per test'
    required: true
  HIDE_WEBDRIVER_LOGS:
    description: 'Hide webdriver logs (1 to hide, 0 to show)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run ${{ inputs.DEVICES_PER_TEST }}-device tests
      id: run-tests
      continue-on-error: true
      shell: bash
      env:
        PLAYWRIGHT_WORKERS_COUNT: ${{ inputs.WORKERS_COUNT }}
        DEVICES_PER_TEST_COUNT: ${{ inputs.DEVICES_PER_TEST }}
      run: |
        echo "Running ${{ inputs.DEVICES_PER_TEST }} tests with ${{ inputs.WORKERS_COUNT }} workers"
        
        grep="(?=.*@${{ inputs.PLATFORM }})(?=.*@${{ inputs.DEVICES_PER_TEST }}-devices)"
        [[ "${{ inputs.RISK }}" != "" ]] && grep="${grep}(?=.*@${{ inputs.RISK }})"
        
        _TESTING=${{ inputs.HIDE_WEBDRIVER_LOGS }} npx playwright test --grep "$grep"

    - name: Upload ${{ inputs.DEVICES_PER_TEST }}-device test results
      uses: ./github/actions/upload-test-results
      with:
        PLATFORM: ${{ inputs.PLATFORM }}
        UPLOAD_IDENTIFIER: devices-${{ inputs.DEVICES_PER_TEST }}-test-run

outputs:
  test-result:
    description: 'Test result (success/failure)'
    value: ${{ steps.run-tests.outcome }}
