// Do not modify this file manually. This file was generated by a script
// at https://github.com/session-foundation/session-shared-scripts
// Translations can be changed at https://getsession.org/translate


/** Right-to-left locale codes */
export const rtlLocales = ['ar', 'fa', 'he', 'ps', 'ur'];

/** All supported Crowdin locale codes */
export const crowdinLocales = [
  'en',
] as const;

/** Crowdin locale type */
export type CrowdinLocale = (typeof crowdinLocales)[number];

/** Type guard for CrowdinLocale */
export function isCrowdinLocale(locale: string): locale is CrowdinLocale {
  return crowdinLocales.indexOf(locale as CrowdinLocale) !== -1;
}
