name: Setup environment for both platforms

description: Setup environment for both platforms (node,deps,start appium)

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install test dependencies
      shell: bash
      run: |
        ls
        git status
        pnpm install --frozen-lockfile

    - name: Start Appium server
      shell: bash
      run: |
        pnpm start-server &
        sleep 5

    - name: Build the tests files
      shell: bash
      run: |
        pnpm tsc
